openapi: 3.0.1
info:
  title: Weather API
  version: "v1"
servers:
  - url: PLUGIN_HOSTNAME
paths:
  /weather:
    get:
      operationId: getWeather
      summary: Get weather information for a city
      parameters:
        - in: query
          name: latitude
          schema:
            type: number
          description: latitude of city
        - in: query
          name: longitude
          schema:
            type: number
          description: longitude of city
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherResponse'


components:
  schemas:
    CurrentWeather:
      type: object
      properties:
        is_day:
          type: integer
          description: 0は夜を示し、1は昼を示します。
        temperature:
          type: number
          format: float
          description: 現在の気温。
        time:
          type: string
          format: date-time
          description: 気温測定の日時。
        weathercode:
          type: integer
          description: |
            天候の状態を示すコード。(WMO Weather interpretation codes)
            WMO Weather interpretation codes (WW)
            |code     |   Description|
            |------|-------|
            |0|	            Clear sky|
            |1, 2, 3|	        Mainly clear, partly cloudy, and overcast|
            |45, 48	 |       Fog and depositing rime fog|
            |51, 53, 55|	    Drizzle: Light, moderate, and dense intensity|
            |56, 57	    |    Freezing Drizzle: Light and dense intensity|
            |61, 63, 65	 |   Rain: Slight, moderate and heavy intensity|
            |66, 67	    |    Freezing Rain: Light and heavy intensity|
            |71, 73, 75	 |   Snow fall: Slight, moderate, and heavy intensity|
            |77	          |  Snow grains|
            |80, 81, 82|	    Rain showers: Slight, moderate, and violent|
            |85, 86	    |    Snow showers slight and heavy|
            |95 *	       | Thunderstorm: Slight or moderate|
            |96, 99 *	    |Thunderstorm with slight and heavy hail|
        winddirection:
          type: number
          format: float
          description: 風向きの角度（度数法）。
        windspeed:
          type: number
          format: float
          description: 風速（km/h）。
    WeatherResponse:
      type: object
      properties:
        current_weather:
          $ref: '#/components/schemas/CurrentWeather'
        elevation:
          type: number
          format: float
          description: 地点の海抜（m）。
        generationtime_ms:
          type: number
          format: float
          description: レスポンスを生成するのにかかった時間（ミリ秒）。
        latitude:
          type: number
          format: float
          description: 緯度。
        longitude:
          type: number
          format: float
          description: 経度。
        timezone:
          type: string
          description: タイムゾーン
        timezone_abbreviation:
          type: string
          description: タイムゾーンの略称
        utc_offset_seconds:
          type: integer
          description: UTCからのオフセット（秒）